---
  - name: 'Copy mod_cluster - mod_advertise.so'
    copy:
      src: 'files/mod_cluster-1.3.1.Final-linux2-x64/mod_advertise.so'
      dest: '{{ httpd_foler }}/modules/mod_advertise.so'
    become: yes

  - name: 'Copy mod_cluster - mod_manager.so'
    copy:
      src: 'files/mod_cluster-1.3.1.Final-linux2-x64/mod_manager.so'
      dest: '{{ httpd_foler }}/modules/mod_manager.so'
    become: yes

  - name: 'Copy mod_cluster - mod_proxy_cluster.so'
    copy:
      src: 'files/mod_cluster-1.3.1.Final-linux2-x64/mod_proxy_cluster.so'
      dest: '{{ httpd_foler }}/modules/mod_proxy_cluster.so'
    become: yes

  - name: 'Copy mod_cluster - mod_cluster_slotmem.so'
    copy:
      src: 'files/mod_cluster-1.3.1.Final-linux2-x64/mod_cluster_slotmem.so'
      dest: '{{ httpd_foler }}/modules/mod_cluster_slotmem.so'
    become: yes

  - name: 'Copy 00-proxy.conf'
    copy:
      src: 'files/00-proxy.conf'
      dest: '{{ httpd_foler }}/conf.modules.d/00-proxy.conf'
    become: yes

  - name: Copy mod_cluster.conf
    become: true
    template:
      src: 'templates/mod_cluster.conf.j2'
      dest: '{{ httpd_foler }}/conf.d/mod_cluster.conf'
    notify:
      - restart httpd
